### ISSUE TITLE
Reproducible Virtual Environment

### ISSUE THREAD

**Issue by hip023** [aleckirkley/Community-Representatives#1]
Hi @aleckirkley !
I'm trying to create a virtual environment to re-produce the code.

Did you use Python 3.8? I'm having a hard time to install graph_tools (any link to a source is highly appreciated, as there's no PyPi package available per my research)

**Comment by aleckirkley** [comment]
Hi Hila, 

Yes, I'm using Python 3.8. There is a nice comprehensive list of installation instructions for graph tool available at https://git.skewed.de/count0/graph-tool/-/wikis/installation-instructions, and if I recall I used the instructions under the 'Conda' subheader. (I know of others who found this the easiest way to install it as well.) 

However, you won't need graph tool for anything but the plotting option, which you can trigger off with the argument graph_plots = False. So if you are unable to install graph tool, it shouldn't be an issue for using the primary part of the code.
